services:

    api:
        build:
            context: .
            dockerfile: docker/api/Dockerfile
            args:
                API_PORT: ${API_PORT}
        image: mp_api:latest
        container_name: mp_api
        env_file:
            - docker/api/.secrets.production.local
        volumes:
            - './docker/users:/usr/src/app/apps/api/users:ro'
        restart: unless-stopped

    portfolio:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
            args:
                API_PORT: ${API_PORT}
        image: mp_portfolio:latest
        container_name: mp_portfolio
        restart: unless-stopped
        depends_on:
            - api
        ports:
            - '${NGINX_PORT}:80'
