version: '3.7'
services: 

    php:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile.prod
        container_name: mp_php_prod
        image: myprofile_php:${TAG}
        volumes:
            - './docker/users:/usr/src/api/resources/users:ro'
        restart: always
        environment:
            HOME: /home/user

    nginx:
        build: 
            context: .
            dockerfile: docker/nginx/Dockerfile.prod
        container_name: mp_nginx_prod
        image: myprofile_nginx:${TAG}
        restart: "always"
        depends_on: 
            - php
        ports: 
            - '${NGINX_PORT}:80'