version: '3.7'
services: 

    app:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile.prod
            args:
                APP_VERSION: ${TAG}   
        container_name: mp_app
        image: mp_app:${TAG}
        volumes:
            - './docker/users:/usr/src/api/resources/users:ro'
        restart: unless-stopped
        environment:
            HOME: /home/user

    web:
        build: 
            context: .
            dockerfile: docker/nginx/Dockerfile.prod
            args:
                APP_VERSION: ${TAG}
        container_name: mp_web
        image: mp_web:${TAG}
        restart: unless-stopped
        depends_on: 
            - app
        ports: 
            - '${NGINX_PORT}:80'