; don't Check PHP Files Timestamps
opcache.validate_timestamps=0

; maximum memory that OPcache can use to store compiled PHP files
opcache.memory_consumption=256

; maximum number of files that can be stored in the cache
opcache.max_accelerated_files=20000

; opcache preloading
opcache.preload_user=www-data
opcache.preload=/usr/src/api/var/cache/prod/App_KernelProdContainer.preload.php
