; don't Check PHP Files Timestamps
opcache.validate_timestamps=0

; opcache preloading
opcache.preload_user=www-data
opcache.preload=/usr/src/api/var/cache/prod/srcApp_KernelProdContainer.preload.php
