
    # PHP Handler
    upstream php-handler {
        server app:9000;
    }
    
server {
    server_name ~.*;
    server_tokens off;

    # Add app version in header response
    add_header X-app_version v%APP_VERSION%;

    # GZip
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json
            application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf
            application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml
            image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component
            text/x-cross-domain-policy;

    # Front - Any routes to index.html
    index index.html;
    location / {
        root /usr/src/front;
        try_files $uri $uri/ /index.html;

        # Cache
        location ~* \.(?:css|js)$ {
            expires 1M;
            add_header        Cache-Control "public";
        }

        location ~* \.(?:jpg|jpeg|gif|png|ico|xml|webp|eot|woff|woff2|ttf|svg|otf)$ {
            access_log        off;
            log_not_found     off;
            expires           1M;
            add_header        Cache-Control "public";
        }

        location ~* \.(?:json)$ {
            access_log        off;
            log_not_found     off;
            expires           1d;
            add_header        Cache-Control "public";
        }
    }

    # API Symfony
    location /api/ {
        root /usr/src/api;
        # Any routes to symfony front
        try_files $uri /api/index.php$is_args$args;

        # PHP FPM
        location ~ ^/api/index\.php(/|$) {
            client_max_body_size 50m;
            fastcgi_pass php-handler;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/src/api/public/index.php;
        }
    }

    error_log /dev/stderr debug;
    access_log /dev/stdout;
}