server {
    server_name ~.*;
    server_tokens off;

    # Add app version in header response
    add_header X-app_version v%APP_VERSION%;

    # GZip
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 0;
    gzip_types text/plain application/javascript text/css application/json application/x-javascript
               text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject
               application/x-font-ttf font/opentype;

    # Front - Any routes to index.html
    index index.html;
    location / {
        root /usr/src/front;
        try_files $uri $uri/ /index.html;

        # Cache
        location ~* \.(?:css|js)$ {
            expires 1M;
            add_header        Cache-Control "public";
        }

        location ~* \.(?:jpg|jpeg|gif|png|ico|json|xml|webp|eot|woff|woff2|ttf|svg|otf)$ {
            access_log        off;
            log_not_found     off;
            expires           1M;
            add_header        Cache-Control "public";
        }
    }

    # API Symfony
    location /api/ {
        root /usr/src/api;
        # Any routes to symfony front
        try_files $uri /api/index.php$is_args$args;

        # PHP FPM
        location ~ ^/api/index\.php(/|$) {
            client_max_body_size 50m;
            fastcgi_pass php:9000;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/src/api/public/index.php;
        }
    }

    error_log /dev/stderr debug;
    access_log /dev/stdout;
}