# Stage1 - Build React App 
FROM node:lts-alpine as build
LABEL maintainer="Julien CROCHET <julien@crochet.me>"

WORKDIR /usr/src/front
RUN apk add --no-cache python make g++
ENV PATH /app/node_modules/.bin:$PATH
COPY apps/front/package.json /usr/src/front/
COPY apps/front/yarn.lock /usr/src/front/
RUN yarn install --prod
COPY apps/front /usr/src/front
COPY docker/node/secrets/.env.production /usr/src/front/
COPY docker/node/.eslintrc.prod /usr/src/front/.eslintrc
ARG APP_VERSION=latest
ENV APP_VERSION $APP_VERSION
RUN yarn build

# Stage 2 - build the final image
FROM nginx:1.18-alpine
LABEL maintainer="Julien CROCHET <julien@crochet.me>"

RUN apk add --no-cache bash && \
    echo 'alias ll="ls -la"' >> ~/.bashrc

WORKDIR /usr/src
COPY apps/api/public /usr/src/api
COPY --from=build /usr/src/front/build /usr/src/front

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
ARG APP_VERSION=latest
RUN sed -e "s/%APP_VERSION%/$APP_VERSION/" /etc/nginx/conf.d/default.conf | tee /etc/nginx/conf.d/default.conf.new && \
    mv /etc/nginx/conf.d/default.conf.new /etc/nginx/conf.d/default.conf

ENV APP_VERSION $APP_VERSION
