# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  versioning: true
  serializer:
    groups: ["Default"]
    serialize_null: false
  exception: false
  view:
    view_response_listener: true
  body_listener:
    enabled: true
  format_listener:
    enabled: true
    rules:
      - {
          path: ^/,
          prefer_extension: false,
          fallback_format: json,
          priorities: [json],
        }
